### ISSUE TITLE
Warnings at build time: No such module "__STATIC_CONTENT_MANIFEST"

### ISSUE THREAD

**Issue by SourLemonJuice** [c-ameron/response-page#5]
```
service core:user:response-page: Uncaught Error: No such module "__STATIC_CONTENT_MANIFEST".
  imported from "index.js"
```

I've run `npm install` and I'm still having problems.

The lack of maintenance is probably why it doesn't have stars...

**Comment by c-ameron** [comment]
This project only works via Cloudflare workers. Have a read through their documentation if you'd like to deploy it.

https://workers.cloudflare.com/

**Comment by SourLemonJuice** [comment]
Sorry, I wasn't clear. But at the time I was indeed running it with `npx wrangler dev`.
It threw some of errors then and now:
some npm install warnings and,
`19 vulnerabilities (12 low level, 1 medium level, 5 high level, 1 critical)`

wrangler said:
```
[mf:wrn] The latest compatibility date for installed Cloudflare Workers Runtime support is “2023-10-25”,
but you requested “2023-11-08”. Fall back to “2023-10-25”...
The compatibility date enabled feature you requested may not be available.
Please upgrade to `wrangler@3.94.0` to remove this warning.
```

Then it throws an error and crashes, or maybe it's just npm magic...

But for now, it throws an error and continues to run in the background(?) after pressing [b] to open the browser.

```
/home/<user>/response-page/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "strategy" argument must be of type object. Received type number (0)
    at new ReadableStream (node:internal/webstreams/readablestream:252:5)
    at safeReadableStreamFrom (/home/<user>/response-page/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:7670:10)
    at #handleLoopback (/home/<user>/response-page/node_modules/wrangler/node_modules/miniflare/dist/src/index.js:7829:36)
    at Server.emit (node:events:519:35)
    at parserOnIncoming (node:_http_server:1146:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
